
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: HElectronics for the Rest of Us! - Henry Challen
description: This is a small sample of the work we did during the week long module, enjoy!

theme: jekyll-theme-hacker
